wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.29
    code_path: code/carla_project/src/traffic_img_model.py
    framework: torch
    is_jupyter_run: false
    python_version: 3.7.13
batch_size:
  desc: null
  value: 16
command_coefficient:
  desc: null
  value: 0.1
dataset_dir:
  desc: null
  value: data/CARLA_challenge_autopilot
hack:
  desc: null
  value: false
heatmap_radius:
  desc: null
  value: 5
id:
  desc: null
  value: c2add4925f22433e99393c5224a9f951
lr:
  desc: null
  value: 0.0001
max_epochs:
  desc: null
  value: 50
sample_by:
  desc: null
  value: even
save_dir:
  desc: null
  value: /scratch/2020_CARLA_challenge/checkpoints/c2add4925f22433e99393c5224a9f951
temperature:
  desc: null
  value: 5.0
weight_decay:
  desc: null
  value: 0.0
